import dns from "dns"; import net from "net";
dns.setDefaultResultOrder("ipv4first");
net.setDefaultAutoSelectFamily(false);
import postgres from "postgres";
import fs from "fs";
const url = fs.readFileSync(".env","utf8").split("\n").find(l=>l.startsWith("DATABASE_URL=")).slice("DATABASE_URL=".length).trim();
const sql = postgres(url, { max: 1, connect_timeout: 30 });
const f = await sql`select id,name,sort_order from features where product_id='uRyrBc_Fjen5XvMcNd2rG' order by sort_order, id`;
console.log("--- features uRyrBc ---"); f.forEach(r=>console.log(r.sort_order, JSON.stringify(r.name), r.id));
const t = await sql`select id,name,sort_order from tiers where product_id='uRyrBc_Fjen5XvMcNd2rG' order by sort_order, id`;
console.log("--- tiers uRyrBc ---"); t.forEach(r=>console.log(r.sort_order, JSON.stringify(r.name), r.id));
await sql.end();
