import postgres from "postgres";
import fs from "fs";
const url = fs.readFileSync(".env","utf8").split("\n").find(l=>l.startsWith("DATABASE_URL=")).slice("DATABASE_URL=".length).trim();
const sql = postgres(url, { max: 1 });
console.log("--- features for uRyrBc ---");
const f = await sql`select id,name,sort_order from features where product_id='uRyrBc_Fjen5XvMcNd2rG' order by sort_order`;
f.forEach(r=>console.log(r.sort_order, JSON.stringify(r.name), r.id));
console.log("--- columns of tiers/features ---");
const cols = await sql`select table_name,column_name from information_schema.columns where table_name in ('tiers','features') order by table_name,ordinal_position`;
cols.forEach(c=>console.log(c.table_name, c.column_name));
console.log("--- products ---");
const p = await sql`select id,name,created_at from products order by created_at`;
p.forEach(r=>console.log(r.id, r.name, r.created_at));
await sql.end();
